version: '3.8'

services:
  oracle-db:
    container_name: oracle-db
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: "teste@123"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
    driver: local
