CREATE TABLE livros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    autor VARCHAR2(255) NOT NULL,
    data_lancamento DATE,
    numero_edicao NUMBER,
    local_lancamento VARCHAR2(255),
    codigo_barras VARCHAR2(100)
);
